### ISSUE TITLE
Using Deep speech

### ISSUE THREAD

**Issue by saran-gangster** [GauravSingh9356/J.A.R.V.I.S#26]
i like this project very much but i feel like speech recognition is very slow even it needs a internet connection so i would recommend
 you to add both online and offline (using [Mozilla deep speech](https://github.com/mozilla/DeepSpeech/releases))
if you need any help in adding this and coding ask me anytime i would love to contribute to this project

**Comment by GauravSingh9356** [comment]
@saran-gangster Thanks for showing interest mate. yeah I will look into it..Yes You also can.and I would really happy to get help

**Comment by saran-gangster** [comment]
this can help you https://github.com/mozilla/DeepSpeech-examples/tree/r0.8/mic_vad_streaming it works on both windows and linux
i have also tested it

**Comment by DHANESHJOSHI** [comment]
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Dhanesh\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>      
    cli.main()
  File "c:\Users\Dhanesh\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in 
main
    run()
  File "c:\Users\Dhanesh\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in 
run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Python39\lib\runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Python39\lib\runpy.py", line 242, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "c:\Users\Dhanesh\Downloads\J.A.R.V.I.S-2.0.1\jarvis.py", line 181
    try:
TabError: inconsistent use of tabs and spaces in indentation

Getting this error please help me brother

**Comment by saran-gangster** [comment]
try not using python 3.9 i would recommend you to use [python 3.8](https://www.python.org/downloads/release/python-385/)

**Comment by saran-gangster** [comment]
> Traceback (most recent call last):
> File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "C:\Python39\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "c:\Users\Dhanesh.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy__main__.py", line 45, in
> cli.main()
> File "c:\Users\Dhanesh.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in
> main
> run()
> File "c:\Users\Dhanesh.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in
> run_file
> runpy.run_path(options.target, run_name=compat.force_str("**main**"))
> File "C:\Python39\lib\runpy.py", line 267, in run_path
> code, fname = _get_code_from_file(run_name, path_name)
> File "C:\Python39\lib\runpy.py", line 242, in _get_code_from_file
> code = compile(f.read(), fname, 'exec')
> File "c:\Users\Dhanesh\Downloads\J.A.R.V.I.S-2.0.1\jarvis.py", line 181
> try:
> TabError: inconsistent use of tabs and spaces in indentation
> 
> Getting this error please help me brother

you are getting this error because of over space see [here](https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation)
mostly sublime text user's get these error
