### ISSUE TITLE
Not Running Properly

### ISSUE THREAD

**Issue by SCcraft21** [GauravSingh9356/J.A.R.V.I.S#47]
When I'm trying to run this it is giving this as an error 
Traceback (most recent call last):
  File "e:\Download\J.A.R.V.I.S-2.0.2\J.A.R.V.I.S-2.0.2\jarvis.py", line 11, in <module>
    from diction import translate
  File "e:\Download\J.A.R.V.I.S-2.0.2\J.A.R.V.I.S-2.0.2\diction.py", line 6, in <module>
    data = json.load(open('data.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'data.json'

What needs to be done please let me know.

**Comment by SCcraft21** [comment]
Just now got another problem
